[package]
name = "tetris"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.13.1", features = ["canvas", "tokio"]}
rand = "0.9.1"
chrono = "0.4.41"
tracing-subscriber = "0.3.19"
